### PR TITLE
Support sortkey

### PR DESCRIPTION
**Pull request by m-vdb**
Hi @shimizukawa 

I needed to support `sortkey` on my model, so I added the support in your module. Let me know if that works for you.

NB: I didn't know how to support the feature on Django < 1.8, so I left it like that. If there is an easy way to do it, please redirect me to it :)

Hope you like it!

### CODE REVIEW

**Comment by m-vdb** [comment]
Actually I realized that this doesn't work with the migration system 😢  still trying to work my way around it, it's not obvious because of [this ticket](https://code.djangoproject.com/ticket/5793)

**Comment by m-vdb** [comment]
ok I've managed to make it work by using the `ordering` Meta option, but for now it doesn't support the `distkey` and the `diststyle`. We could leverage them in Django 1.11 if we use the [Meta.indexes](https://docs.djangoproject.com/en/1.11/ref/models/options/#indexes) option and tweak it a little bit. Just a thought :)

**Comment by jdkanani** [comment]
This is fantastic. Please merge it :)

**Comment by Surgo** [comment]
does redshift support sortkey multiple? maybe no

**Comment by m-vdb** [comment]
apparently the code I wrote doesn't support multiple sortkeys (it outputs what I believe is invalid Redshift SQL: `SORTKEY(col1) SORTKEY(col2)`). To be able to support multiple sortkeys, the code need to output `SORTKEY(col1, col2)` [here](https://github.com/m-vdb/django-redshift-backend/blob/ff183e73a82d1925969a0b0faaeaefbdd9cbb110/django_redshift_backend/base.py#L471)

**Pull request merged**
